- hosts: MyClient
  tasks:
    - name: install httpd
      action: yum name=httpd state=installed
    - name: copy index.html
      copy: src=files/index.html dest=/var/www/html/index.html
    - name: start apache
      service:
       name: httpd
       state: restarted
